

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*		Themify Framework v.1.1.0
/*		http://themify.me
/*		
/*		Copyright 2011, Darcy Clarke
/*		Dual licensed under the MIT or GPL Version 2 licenses.
/*		http://themify.me/license.txt
/*
/***************************************************************************/

///////////////////////////////////////////
// Check noConlifct var exists 
///////////////////////////////////////////
if(themify === undefined) 
	var themify = jQuery.noConflict();

///////////////////////////////////////////
//
// Peter Higgins Pub/Sub
// https://github.com/phiggins42/bloody-jquery-plugins/blob/master/pubsub.js
//
///////////////////////////////////////////
;(function(d){
	var cache = {};
	d.publish = function(topic, args){
		cache[topic] && d.each(cache[topic], function(){
			this.apply(d, args || []);
		});
	};
	d.subscribe = function(topic, callback){
		if(!cache[topic]){
			cache[topic] = [];
		}
		cache[topic].push(callback);
		return [topic, callback];
	};
	d.unsubscribe = function(handle){
		var t = handle[0];
		cache[t] && d.each(cache[t], function(idx){
			if(this == handle[1]){
				cache[t].splice(idx, 1);
			}
		});
	};
})(themify);

///////////////////////////////////////////
// Create conflict-free jQuery environment 
///////////////////////////////////////////
themify(function($){  
	
	$.publish("themify_init", [this]);
	
	
	/*******************************************************************************/
	/* Tab Events */
	
	///////////////////////////////////////////
	// Create Tabs
	///////////////////////////////////////////
	$('#content, .maintab').tabs({ fx: { opacity: 'toggle', duration: 200 }, cache: false });
	$('#content').bind("tabsshow", function(event, ui) { 
		if(ui.tab.hash == "#setting" || ui.tab.hash == "#styling" || ui.tab.hash == "#skins" || ui.tab.hash == "#transfer"){
			window.location.hash = ui.tab.hash;	
		}
		$.publish("themify_tab_change", [this]);
		$("body").animate({scrollTop:0}, 1);
	});
	$("body").animate({scrollTop:0}, 1);
	
	/*******************************************************************************/
	/* Global Events  */
	
	///////////////////////////////////////////
	// Save
	///////////////////////////////////////////
	$('.save-button').bind('click', function(e){
		e.preventDefault();						 
		showAlert();
		$.publish("themify_before_save");
		var data = $('#themify').serialize();
		$.post(ajaxurl, { action: "themify_save", "data": data }, function(data){
			$.publish("themify_after_save");
			hideAlert();
		});
	});
	
	///////////////////////////////////////////
	// Reset Styling
	///////////////////////////////////////////
	$("#reset-styling").live('click', function(e){
		e.preventDefault();
		var reply = confirm("Are you sure you want to reset your theme style?");
		if(reply){
			showAlert();
			$.post(ajaxurl, { action: "themify_reset_styling", "data": $('#themify').serialize() }, function(data){
				hideAlert();
				window.location.reload(true);
			});									   
		}
	});
	
	///////////////////////////////////////////
	// Reset Setting
	///////////////////////////////////////////
	$("#reset-setting").live('click', function(e){
		e.preventDefault();
		var reply = confirm("Are you sure you want to reset your theme settings?");
		if(reply){
			showAlert();
			$.post(ajaxurl, { action: "themify_reset_setting", "data": $('#themify').serialize() }, function(data){
				hideAlert();
				window.location.reload(true);
			});									   
		}
	});
	
	///////////////////////////////////////////
	// Upgrade Theme / Framework
	///////////////////////////////////////////
	$(".upgrade-framework, .upgrade-theme").live('click', function(e){
		e.preventDefault();
		var reply = confirm("Make sure to backup before upgrading. Files and settings may get lost or changed."), 
			el = $(this);
		if($(this).hasClass('upgrade-theme')){
			var type = "theme";
		} else {
			var type = "framework";	
		}
		if($(this).parent().hasClass('login')){
			var login = true;	
		} else {
			var login = false;	
		}
		if(reply){
			if(login){
				showLogin();
			} else {
				showAlert();
				$.post(ajaxurl, { action: "themify_updater", 'type':type,'login':"false"}, function(data){
					if(data != 'false'){
						hideAlert();
						if(type == "theme"){
							window.location = themify.blog_url + "wp-admin/admin.php?page=themify&success=true&upgrade_type=theme";
						} else {
							window.location = themify.blog_url + "wp-admin/admin.php?page=themify&success=true&upgrade_type=framework";
						}
					} else {
						hideAlert('error');	
					}
				});	
			}
		}
	});
	
	///////////////////////////////////////////
	// Login Validation
	///////////////////////////////////////////
	$(".upgrade-login").live('click', function(e){
		e.preventDefault();										   
		var el = $(this), 
			username = el.parent().parent().find('.username').val(),
			password = el.parent().parent().find('.password').val(),
			login = $(".upgrade-theme").parent().hasClass('login');
		if(username != "" && password != ""){
			hideLogin();
			showAlert();
			$.post(ajaxurl, { action: "themify_updater", 'type':'theme','login':login,'username':username,'password':password}, function(data){
				if(data != 'false'){
					hideAlert();
					window.location = themify.blog_url + "wp-admin/admin.php?page=themify&success=true&upgrade_type=theme";
				} else {
					hideAlert('error');	
					showLogin('error');
				}
			});																					
		} else {
			hideAlert('error');	
			showLogin('error');							   
		}
	});
	
	///////////////////////////////////////////
	// Hide Overlay
	///////////////////////////////////////////
	$(".overlay").live('click', function(){
		hideLogin();
	});
	
	///////////////////////////////////////////
	// Valid Numbers
	///////////////////////////////////////////
	$('.valid_num').keyup(function(e){
		var el = $(this);
		if(!is_numeric(el.val())){
			el.val(el.val().substring(0,(el.val().length-1)));	
		}
	}).live("input paste", function(e){
		$(this).trigger("keyup");
	});
	
	/*******************************************************************************/
	/* Uploadify Events */
	
	///////////////////////////////////////////
	// Create Instances for Upload
	///////////////////////////////////////////
	$(".upload-image").each(function(){
		var el = $(this), folder = el.parent().parent().find(".target").text();
		if(folder == "" || folder == undefined){
			folder = "uploads/";	
		}
		$("#" + el.attr('id')).uploadify({
			"uploader"      : themify.app_url + "js/uploadify.swf",
			"script"        : ajaxurl,
			"cancelImg"     : themify.app_url + "img/cancel.png",
			"folder"        : "",
			"scriptData"	: {"action": "themify_upload", "target":folder},
			"height"		: "20",
			"width"			: "70",
			"method"		: "POST",
			"hideButton"	: true,
			"wmode"			: "transparent",
			"fileDesc"		: "Image Files",
			"fileExt"		: "*.jpg;*.jpeg;*.gif;*.png",
			"multi"			: true,
			"sizeLimit"		: 100 * 1024 * 1024,
			"auto"          : true
		});
		$("#" + el.attr('id')).bind({
			"uploadifySelect" : function(event, id, file){
				themify.complete_status = false;
				$.publish("themify_upload_select", [this]);
				showAlert();
			},
			"uploadifyOpen" : function(event, id, file){
				$.publish("themify_upload_open", [this]);
			},
			"uploadifyError" : function(event, id, file, error){
				$.publish("themify_upload_error", [this]);
			},
			"uploadifyProgress" : function(event, id, file, data){
				$.publish("themify_upload_progress", [this]);
			},
			"uploadifyCancel" : function(event, id, file, data){
				$.publish("themify_upload_cancel", [this]);
				hideAlert('error');
			},
			"uploadifyComplete" : function(event, id, file, response, data){
				console.log(response + " : ", data);
				if(!response || response == false){
					hideAlert('error');
					themify.complete_status = true;
				} else {
					if(themify.complete_status == false){
						$.publish("themify_upload_complete", [this]);
						hideAlert();
						response = response.replace("%uFEFF","");
						var path = themify.theme_url + folder + $.trim(decodeURI(response)), 
						title = folder + $.trim(decodeURI(response)),
						el = $('<a href="#" style="display:none;" title="' + title + '"><span title="' + title + '"></span><img src="' + themify.app_url + 'img.php?w=50&h=50&src=' + path + '" alt="' + path + '" class="backgroundThumb selected"  /></a>').fadeIn(1000);
						if($(this).hasClass('favicon')){
							$(this).parent().parent().parent().find('input').val(path);
						} else if($(this).hasClass('simple')) {
							$(this).parent().parent().find('input.feature_box_img').val(path);
						} else if($(this).hasClass('logo')) {
							$(this).parent().parent().find('.image:first input').val(path);
						} else {
							$(this).parent().parent().parent().find('.backgroundThumb.selected').removeClass('selected');
							$(this).parent().parent().parent().find('.preset').prepend(el);
							$(this).parent().parent().parent().find('.background_image input').removeAttr('disabled').val(path);
							$(this).parent().parent().parent().find('.background_image input:checkbox').attr('checked', false);
						}
						themify.complete_status = true;
					}
				}
			}
		});
	});
	
	///////////////////////////////////////////
	// Cancel Upload
	///////////////////////////////////////////
	//$(".upload-action-cancel").bind("click", function(e){
//		e.preventDefault();
//		$(".upload-file").uploadifyClearQueue();
//		$.publish("themify_upload_cancel", [this]);
//	});

	
	/*******************************************************************************/
	/* Style Module Events */
	
	///////////////////////////////////////////
	// Padding / Margin
	///////////////////////////////////////////
	$('.padding-switch, .margin-switch').click(function(){
		var el = $(this), parent = el.parent().parent().parent(), num = 0;
		if(el.is(":checked")){
			if(parent.find(".individuals input:first").val() != ''){
				num = parent.find(".individuals input:first").val();
			}
			parent.find(".individuals").fadeOut(200, function(){ 
				parent.find(".same").fadeIn(200).find("input").val(num); 
			}).find("input").val('');
		} else {
			if(parent.find(".same input").val() != ''){
				num = parent.find(".same input").val();
			}
			parent.find(".same").fadeOut(200, function(){
				parent.find(".individuals").fadeIn(200).find("input").val(num);					
			}).find("input").val('');
		}
	});
	
	///////////////////////////////////////////
	// Border
	///////////////////////////////////////////
	$('.border-switch').bind("click",function(e){
		var el = $(this), parent = el.parent().parent().parent(), color = '', num = 0;
		if(el.is(":checked")){
			if(parent.find(".individuals input[type=text]:nth-child(1)").val() != ''){
				color = parent.find(".individuals input[type=text]:nth-child(1)").val();
			}
			if(parent.find(".individuals input:nth-child(2)").val() != ''){
				num = parent.find(".individuals input:nth-child(2)").val();
			}
			var true_color = parent.find(".individuals .colorSelect").css('background-color');
			parent.find(".individuals .colorSelect").css('background-color','#ffffff');
			parent.find(".individuals input[type=text]").val('');
			parent.find(".individuals").fadeOut(200, function(){
				parent.find(".same input[type=text]:nth-child(1)").val(color);
				parent.find(".same .colorSelect").css("background-color",true_color);
				parent.find(".same").fadeIn(200).find("input:nth-child(2)").val(num);
				parent.find(".same select").val(parent.find('.individuals select:first option:selected').val());
			});	
		} else {
			if(parent.find(".same input[type=text]:nth-child(1)").val() != ''){
				color = parent.find(".same input[type=text]:nth-child(1)").val();
			}
			if(parent.find(".same input:nth-child(2)").val() != ''){
				num = parent.find(".same input:nth-child(2)").val();
			}
			var true_color = parent.parent().find(".same .colorSelect").css('background-color');
			parent.find(".same .colorSelect").css('background-color','#ffffff');
			parent.find(".same input").val('');
			parent.find(".same").fadeOut(200, function(){
				parent.find(".individuals select").val(parent.parent().find('.same select:first option:selected').val());
				parent.find(".individuals").fadeIn(200).find("input[type=text]:nth-child(2)").val(num);
				parent.find(".individuals .borders input[type=text]:nth-child(1)").val(color);
				parent.find(".individuals .borders .colorSelect").css("background-color",true_color);
			});
		}
	});
	
	///////////////////////////////////////////
	// Background-Color Transparent
	///////////////////////////////////////////
	$('.colorTransparent').bind("click",function(e){
		var el = $(this);
		if(el.is(":checked")){
			el.parent().find("input[type=text]").attr('disabled', true).val('').parent().find(".colorSelect").css('background-color','#ffffff');
			$.publish("themify_enable_background_color_transparent", [this]);
		} else {
			el.parent().find("input[type=text]").removeAttr('disabled');	
			$.publish("themify_disable_background_color_transparent", [this]);
		}
	});
	
	///////////////////////////////////////////
	// Background-Position 
	///////////////////////////////////////////
	$('.background_position.positionX').bind("change",function(){
		$(this).parent().find('.valueX').val($('option:selected', this).val());
		$.publish("themify_select_background_position_x", [this]);
	});
	$('.background_position.positionY').bind("change",function(){
		$(this).parent().find('.valueY').val($('option:selected', this).val());
		$.publish("themify_select_background_position_y", [this]);
	});
	
	///////////////////////////////////////////
	// Background-Image Thumb
	///////////////////////////////////////////
	$('.backgroundThumb').live("click",function(e){
		e.preventDefault();
		var el = $(this), alt = el.attr("alt");
		el.parent().parent().find('.backgroundThumb.selected').removeClass('selected');
		el.addClass('selected');
		el.parent().parent().parent().find('.background_image input').removeAttr('disabled').val(alt);
		el.parent().parent().parent().find('.background_image input:checkbox').attr('checked', false);
		$.publish("themify_select_background_image", [this]);
	});
	
	///////////////////////////////////////////
	// Background-Image Remove Selection on Blur
	///////////////////////////////////////////
	$('.background_image .upload-file').live("blur",function(e){
		var el = $(this);
		if(el.val() == ''){
			el.parent().parent().find('.backgroundThumb.selected').removeClass('selected');
		}
	});
	
	///////////////////////////////////////////
	// Background-Image None
	///////////////////////////////////////////
	$('.background_image input:checkbox').live("click",function(){
		var el = $(this);
		$.publish("themify_select_background_image_none", [this]);
		if(el.is(":checked")){
			el.parent().parent().find('.backgroundThumb.selected').removeClass('selected');
			el.parent().parent().find('.background_image input[type=text]').attr('disabled', true).val('');							  
		} else {
			el.parent().parent().find('.background_image input[type=text]').removeAttr('disabled');
		}
	});
	
	///////////////////////////////////////////
	// Delete Image
	///////////////////////////////////////////
	$('.preset a span').live("click",function(e){
		e.preventDefault();
		el = $(this);
		var reply = confirm("Do you want to delete this image permanently?");
		if(reply){
			$.publish("themify_delete_image", [this]);
			$.post(ajaxurl, { action: "themify_delete_image", "file": el.attr("title") }, function(data){
				if(el.parent().parent().parent().find('.background_image input[type=text]').val() == el.parent().find("img").attr("alt")){
					el.parent().parent().parent().find('.background_image input[type=text]').val('');	
				}
				el.parent().remove();
			});	
		}
	});
	
	///////////////////////////////////////////
	// Position
	///////////////////////////////////////////
	$('.select_position').bind("change", function(){
		var val = $('option:selected', this).val();
		if(val == 'absolute' || val == 'fixed'){
			$(this).parent().parent().find('.position_display').show(200);	
		} else {
			$(this).parent().parent().find('.position_display').hide(200);	
		}
		$.publish("themify_select_position", [this]);
	});
	
	///////////////////////////////////////////
	// Color Picker
	///////////////////////////////////////////
	$('.colorSelectInput').live('blur', function(){
		var temp = $(this);
		if(temp.val() == ''){
			var color = "#ffffff";	
		} else {
			var color = "#"+temp.val();	
		}
		temp.parent().find(".colorSelect").ColorPickerSetColor(temp.val()).css('background-color',color);
	});
	$('.colorSelect').ColorPicker({
		onBeforeShow: function(hsb, hex, rgb){
			themify.current_obj = this;
			$(this).ColorPickerSetColor($(this).parent().find(".colorSelectInput").val());
		},
		onShow: function (colpkr) {
			$(colpkr).fadeIn(200);
			return false;
			$.publish("themify_show_colorpicker", [this]);
		},
		onHide: function (colpkr) {
			var temp = $(themify.current_obj);
			var val = $(colpkr).find(".colorpicker_hex input[type=text]").val();
			temp.css({'background-color':"#"+val});
			temp.parent().find("input[type=text]:first").val(val);
			$(colpkr).fadeOut(200);
			return false;
			$.publish("themify_hide_colorpicker", [this]);
		}
	});
	
	///////////////////////////////////////////
	// Font-Family - Old
	///////////////////////////////////////////
	$('.fontFamily').bind("change",function(){
		var el = $(this);
		if($('option:selected', this).val() == 'custom'){
			el.parent().find('.value').show();
			el.parent().find('.value input').val('');
		} else {
			el.parent().find('.value').hide();
			el.parent().find('.value input').val($('option:selected', this).val());
		}
		$.publish("themify_select_font_family", [this]);
	});
	
	///////////////////////////////////////////
	// Create Font Family Dropdowns
	///////////////////////////////////////////
	$(".fontFamily").each(function(i, el){
		var el = $(this), div = $("<div class='fontFamilyList'><a href='#' class='selected'></a><ul></ul></div>"), selected = '', ul = $("ul",div.insertBefore(el));
		
		$("option",el).each(function(i, el){
			var el = $(this), select = (selected == el) ? " selected" : "";
			if(el.is(":selected")){
				selected = el.text();
			}
			$("<li class='option'><a href='#' title='" + el.text() + "' style='font-family:" + el.text() + "'>" + el.text() + "</a></li>").appendTo(ul);
		});
		
		$(".selected", div).text(selected).css("font-family", selected);
		el.hide();
	});
	
	$(".fontFamilyList .selected").bind("click", function(e){
		e.preventDefault();
		var el = $(this), div = el.parent(), ul = $("ul", div);
		if(ul.is(":hidden")){
			ul.fadeIn(200);
		} else {
			ul.fadeOut(200);
		}
	});
	
	$(".fontFamilyList ul li a").bind("click", function(e){
		e.preventDefault();
		var el = $(this), ul = el.parent().parent(), div = ul.parent(), selected = $(".selected", div);
		
		$(".fontFamily option:selected", div.parent()).removeAttr("selected");
		$(".fontFamily option[value="+ el.text() +"]", div.parent()).attr('selected','selected');
		
		selected.text(el.text()).css("font-family",el.text());
		ul.fadeOut(200);
	});
	
	$(".fontFamilyList").bind("clickoutside", function(e){
		$("ul", this).fadeOut(200);
	});
	
	///////////////////////////////////////////
	// Site-Logo
	///////////////////////////////////////////
	$("input[name='setting-site_logo']").bind("change",function(){
		var el = $(this);
		if(el.val() == "image"){
			el.parent().parent().find(".image").fadeIn(200);
			el.parent().parent().find(".image").css("display","block");
			$.publish("themify_enable_site_logo_image", [this]);
		} else {
			el.parent().parent().find(".image").fadeOut();
			$.publish("themify_enable_site_logo_text", [this]);
		}
	});
	
	///////////////////////////////////////////
	// Feature Box Image / Posts Display
	///////////////////////////////////////////
	$(".feature-box-display").bind("click",function(){
		var el = $(this);
		if(el.val() == "images"){
			el.parent().parent().find(".feature_box_posts").fadeOut(200, function(){
				$(this).parent().parent().find(".feature_box_images").fadeIn(200);						
				$.publish("themify_enable_feature_box", [this]);	
			});
		} else {
			el.parent().parent().find(".feature_box_images").fadeOut(200, function(){
				$(this).parent().parent().find(".feature_box_posts").fadeIn(200);		
				$.publish("themify_disable_feature_box", [this]);
			});
		}
	});
	
	///////////////////////////////////////////
	// Feature Box Enabled Display
	///////////////////////////////////////////
	$(".feature_box_enabled_check").bind("click",function(){
		if($(this).is(":checked")){
			$(this).parent().parent().find(".feature_box_enabled_display").fadeIn(200);
			$.publish("themify_enable_feature_box", [this]);
		} else {
			$(this).parent().parent().find(".feature_box_enabled_display").fadeOut(200);
			$.publish("themify_disable_feature_box", [this]);
		}
	});
	
	///////////////////////////////////////////
	// Layout Options 
	///////////////////////////////////////////
	$(".preview-icon").bind("click",function(e){
		e.preventDefault();
		$(this).parent().find(".selected").removeClass("selected");
		$(this).addClass("selected");
		$(this).parent().find(".val").val($(this).find("img").attr("alt"));
		$.publish("themify_select_thumb", [this]);
	});
	
	/*******************************************************************************/
	/* Skin CSS Load */
	
	///////////////////////////////////////////
	// Skins Load
	///////////////////////////////////////////
	$(".skin-preview").bind("click",function(e){
		e.preventDefault();
		$(".skin-preview img.selected").removeClass();
		$(this).find("img").addClass('selected');
		$("input[name='skin']").val($(this).find("img").attr('id'));
		$.publish("themify_select_skin", [this]);
	});
	
	
	/*******************************************************************************/
	/* Exporting Events */
	
	///////////////////////////////////////////
	// Export Download
	///////////////////////////////////////////
	$("#download-export").bind("click",function(e){
		e.preventDefault();
		$.publish("themify_export", [this]);
		window.open(themify.app_url + "themify-ajax.php?export=true");
	});
	
	/*******************************************************************************/
	/* Importing Events */
	
	///////////////////////////////////////////
	// Importing
	///////////////////////////////////////////
	$("#download-import").uploadify({
		"uploader"      : themify.app_url + "js/uploadify.swf",
		"script"        : ajaxurl,
		"cancelImg"     : themify.app_url + "img/cancel.png",
		"folder"        : "temp",
		"scriptData"	: {action: "themify_import"},
		"cancelImg"		: "cancel.png",
		"height"		: "60",
		"width"			: "174",
		"method"		: "POST",
		"hideButton"	: true,
		"wmode"			: "transparent",
		"multi"			: true,
		"sizeLimit"		: 100 * 1024 * 1024
	});
	
	$("#download-import").bind({
		"uploadifySelect" : function(event, id, file){
			var reply = confirm("Import will overwrite all settings and configurations. Press OK to continue, Cancel to stop.");
			if(reply){
				$.publish("themify_upload_import_select", [this]);
				$("#download-import").uploadifyUpload();
				themify.complete_status = false;
				showAlert();
			}
		},
		"uploadifyOpen" : function(event, id, file){
			$.publish("themify_upload_import_open", [this]);
		},
		"uploadifyError" : function(event, id, file, error){
			$.publish("themify_upload_import_error", [this]);
		},
		"uploadifyProgress" : function(event, id, file, data){
			$.publish("themify_upload_import_progress", [this]);
		},
		"uploadifyCancel" : function(event, id, file, data){
			$.publish("themify_upload_import_cancel", [this]);
			hideAlert();
		},
		"uploadifyComplete" : function(event, id, file, response, data){
			if($.themify.complete_status == false){
				$.publish("themify_upload_import_complete", [this]);
				hideAlert();
				$.themify.complete_status = true;
				window.location.reload(true);
			}
		}
	});
	
	/*******************************************************************************/
	/*	Display Alerts */
	
	///////////////////////////////////////////
	// Display Login
	///////////////////////////////////////////
	function showLogin(status){
		if(status == 'error'){
			$.publish("themify_login_error", [this]);
			if($('.prompt-box .prompt-error').length == 0){
				$('.prompt-box .prompt-msg').after('<p class="prompt-error">There was an error, please check your information</p>');
			}
		} else {
			$('.prompt-box .prompt-error').remove();
		}
		$.publish("themify_before_show_login");
		$(".overlay, .prompt-box").fadeIn(500, function(){
			$.publish("themify_after_show_login", [this]);
		});	
	}	
	
	///////////////////////////////////////////
	// Hide Login
	///////////////////////////////////////////
	function hideLogin(){
		$.publish("themify_before_hide_login");
		$(".overlay, .prompt-box").fadeOut(500, function(){
			$.publish("themify_after_hide_login", [this]);
		});
	}
	
	///////////////////////////////////////////
	// Display Alert
	///////////////////////////////////////////
	function showAlert(){
		$.publish("themify_before_show_alert");
		$(".alert").addClass("busy").fadeIn(800, function(){
			$.publish("themify_after_show_alert", [this]);
		});
	}
	
	///////////////////////////////////////////
	// Hide Alert
	///////////////////////////////////////////
	function hideAlert(status){
		if(status == 'error'){
			$.publish("themify_alert_error");
			status = 'error';	
		} else {
			status = 'done';	
		}
		$.publish("themify_before_hide_alert", [this]);
		$(".alert").removeClass("busy").addClass(status).delay(800).fadeOut(800, function(){
			$.publish("themify_after_hide_alert", [this]);
			$(this).removeClass(status);											   
		});	
	}
	
	/*******************************************************************************/
	/*	Is Numeric Function */
	
	function is_numeric(string){
		var ValidChars = " 0123456789.+-";
		var IsNumber = true;
		var Char;
		for (i = 0; i < string.length && IsNumber == true; i++){ 
			Char = string.charAt(i); 
			if(ValidChars.indexOf(Char) == -1){
				IsNumber = false;
			}
		}
		return IsNumber;
	}

}); 
