<?php

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*		Themify Framework v.1.1.0
/*		http://themify.me
/*		
/*		Copyright 2011, Darcy Clarke
/*		Dual licensed under the MIT or GPL Version 2 licenses.
/*		http://themify.me/license.txt
/*
/***************************************************************************/

/* 	AJAX
/***************************************************************************/
		
	error_reporting(0);		
	
	///////////////////////////////////////////
	// Placeholders
	///////////////////////////////////////////
	if(!function_exists('add_action')){
		function add_action($action, $function){
			return true;
		}
	}
	if(!function_exists('do_action')){
		function do_action($action){
			return true;
		}
	}
	if(!function_exists('add_shortcode')){
		function add_shortcode($shortcode, $function){
			return true;
		}
	}
	
	///////////////////////////////////////////
	// Extract
	///////////////////////////////////////////
	function themify_export(){
		
		define('TEMPLATEPATH', realpath(dirname(__FILE__)."/../"));
		define('ABSPATH', dirname(__FILE__)."/includes/");
		$check = true;
		
		if(file_exists('../../../../wp-config.php')){
			require_once('../../../../wp-config.php');
		} else if(file_exists('../../../../../wp-config.php')){
			require_once('../../../../../wp-config.php');
		} else {
			$check = false;
		}
		require_once('themify-database.php');
		
		require_once('themify-utilities.php');
		
		$theme = themify_get_skin_info('../style.css');
		global $themify_globals;
		if(!isset($themify_globals)){
			$themify_globals = array();
		}
		if(!isset($themify_globals['theme'])){
			$themify_globals['theme'] = array();
			$themify_globals['theme']['Name'] = trim($theme['Theme Name']);
		}
		$theme = $themify_globals['theme'];
		
		if($check){
			
			if(class_exists('ZipArchive')){
				$datafile = "data_export.txt";
				$handler = fopen($datafile, 'w');
				fwrite($handler,serialize(themify_get_data()));
				fclose($handler);
				$files_to_zip = array(
					'../custom-styles.css',
					'../theme-config.xml',
					'../theme-functions.php',
					'../theme-modules.php',
					'../custom-config.xml',
					'../custom-functions.php',
					'../custom-modules.php',
					'../custom-widgets.php',
					$datafile
				);
				$file = $theme['Name'].'_themify_export_'.date("Y-m-d").'.zip';
				$result = themify_create_zip($files_to_zip, $file, true);
				if($result){
					themify_force_download($file);
					unlink($datafile);
					unlink($file);
				}
			} else {
				if(ini_get('zlib.output_compression')) { 
					ini_set('zlib.output_compression', 'Off');	
				}
				header('Pragma: public');
				header('Expires: 0');
				header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
				header('Cache-Control: private',false);
				header('Content-Type: application/force-download');
				header('Content-Disposition: attachment; filename="'.$theme['Name'].'_themify_export_'.date("Y-m-d").'.txt"');
				header('Content-Transfer-Encoding: binary');
				echo serialize(themify_get_data());
				exit();
			}
		}
	}
	
	if($_GET['export']){
		themify_export();
	}
	
	///////////////////////////////////////////
	// Save Settings
	///////////////////////////////////////////
	add_action('wp_ajax_themify_save', 'themify_exec_save');
	function themify_exec_save(){
		do_action('themify_before_save');
		$data = explode("&", $_POST['data']);
		$temp = array();
		
		//
		// potential pain point to + javascript footer
		//
		
		foreach($data as $a){
			$v = explode("=", $a);
			$temp[$v[0]] = str_replace("+"," ",preg_replace('/%([0-9a-f]{2})/ie', "chr(hexdec('\\1'))", $v[1]));
		}
		themify_set_data($temp);
		do_action('themify_after_save');
		echo "true";
	}
	
	///////////////////////////////////////////
	// Reset Styling
	///////////////////////////////////////////
	add_action('wp_ajax_themify_reset_styling', 'themify_exec_reset_styling');
	function themify_exec_reset_styling(){
		do_action('themify_before_reset_styling');
		$data = explode("&", $_POST['data']);
		$temp_data = array();
		foreach($data as $a){
			$v = explode("=", $a);
			$temp_data[$v[0]] = str_replace("+"," ",preg_replace('/%([0-9a-f]{2})/ie', "chr(hexdec('\\1'))", $v[1]));
		}
		$temp = array();
		foreach($temp_data as $key => $val){
			if(strpos($key, 'styling') === false){
				$temp[$key] = $val;
			}
		}
		do_action('themify_after_reset_styling');
		print_r(themify_set_data($temp));	
	}
	
	///////////////////////////////////////////
	// Reset Setting
	///////////////////////////////////////////
	add_action('wp_ajax_themify_reset_setting', 'themify_exec_reset_setting');
	function themify_exec_reset_setting(){
		do_action('themify_before_reset_setting');
		$data = explode("&", $_POST['data']);
		$temp_data = array();
		foreach($data as $a){
			$v = explode("=", $a);
			$temp_data[$v[0]] = str_replace("+"," ",preg_replace('/%([0-9a-f]{2})/ie', "chr(hexdec('\\1'))", $v[1]));
		}
		$temp = array();
		foreach($temp_data as $key => $val){
			if(strpos($key, 'setting') === false){
				$temp[$key] = $val;
			}
		}
		do_action('themify_after_reset_setting');
		print_r(themify_set_data($temp));	
	}
	
	///////////////////////////////////////////
	// Import
	///////////////////////////////////////////
	add_action('wp_ajax_themify_import', 'themify_exec_import');
	function themify_exec_import(){
		do_action('themify_before_import');
		if(!empty($_FILES)) {
			if(!is_dir(get_template_directory().'/themify/temp')){		
				mkdir(get_template_directory().'/themify/temp', 0777);
			}
			if(move_uploaded_file($_FILES['Filedata']['tmp_name'], get_template_directory().'/themify/temp/'.basename($_FILES['Filedata']['name']))){
				$file = basename($_FILES['Filedata']['name']);
				$ext = substr(strrchr($file, '.'), 1);
				$dir = "temp/";
				if($ext == 'zip' || $ext == 'rar'){
					themify_extract_zip(get_template_directory().'/themify/'.$dir.$file);
				} else if($ext == 'txt'){
					$handler = fopen($dir.$file, 'r');
					if(filesize($dir.$file) > 0){
						$data = fread($handler, filesize($dir.$file));
						set_data(unserialize($data));
					}
					fclose($fh);	
				}
				$handle = opendir("temp/");
   				while($file = readdir($handle)){
      				if($file != "." && $file != ".."){
            			unlink("temp/".$file);
					}
				}
				rmdir("temp/");
				echo "true";
			} else {
				echo "false";
			}
		}
		do_action('themify_after_import');	
	}

	///////////////////////////////////////////
	// Upload Image
	///////////////////////////////////////////
	add_action('wp_ajax_themify_upload', 'themify_exec_upload');
	function themify_exec_upload(){
		echo "test";
		do_action('themify_before_image_upload');
		echo get_template_directory().'/uploads/';
		if(!empty($_FILES)) {
			if(!isset($_POST['target']) || $_POST['target'] == ''){
				$target = get_template_directory().'/uploads/';
			} else {
				$target = get_template_directory().'/'.$_POST['target'];
			}	
			$target = rtrim($target, "/");
			$check = false;
			if(!is_dir($target)){		
				if(!mkdir($target, 0777, true)){
					echo "false";	
				} else {
					$check = true; 	
				}
			} else {
				$check = true;	
			}
			if($check){
				if(move_uploaded_file($_FILES['Filedata']['tmp_name'], $target."/".str_replace(" ", "-", basename($_FILES['Filedata']['name'])))){
					echo str_replace(" ", "-", basename($_FILES['Filedata']['name']));
				} else {
					echo "false";
				}
			}
		}
		do_action('themify_after_image_upload');
	}
	
	///////////////////////////////////////////
	// Upload Image - To Wordpress Uploads
	///////////////////////////////////////////
	add_action('wp_ajax_themify_upload_wordpress', 'themify_exec_upload_wordpress');
	function themify_exec_upload_wordpress(){
		do_action('themify_before_wp_image_upload');
		if(!empty($_FILES)){
			$filename = $_FILES["Filedata"]["tmp_name"];
			$file = fopen($filename, 'r');
			$data = fread($file, filesize($filename));
			fclose($file);
			$upload = wp_upload_bits($_FILES["Filedata"]["name"], null, $data);
			if($upload['error']){
				echo $upload['error'];	
			} else {
				echo $upload['url'];
			}
		} else {
			echo "false";	
		}	
		do_action('themify_after_wp_image_upload');
	}
	
	///////////////////////////////////////////
	// Delete Image
	///////////////////////////////////////////
	add_action('wp_ajax_themify_delete_image', 'themify_exec_delete_image');
	function themify_exec_delete_image(){
		do_action('themify_before_delete_image');
		if(file_exists("../".$_POST['file'])){
			unlink("../".$_POST['file']);
			echo "true";
		} else {
			echo "false";	
		}
		do_action('themify_after_delete_image');	
	}
	
	///////////////////////////////////////////
	// Version Updater
	///////////////////////////////////////////
	add_action('wp_ajax_themify_updater', 'themify_exec_updater');
	function themify_exec_updater(){
		global $themify_globals;
		$theme = $themify_globals['theme'];
		if($_POST['type'] == 'theme'){
			$url = 'http://themify.me/files/'.strtolower($theme['Name']).'/'.strtolower($theme['Name']).'.zip';
			$dest = "../../";
		} else if($_POST['type'] == 'framework'){
			$url = 'http://themify.me/files/themify/themify.zip';
			$dest = "../";
		}
		if($_POST['login'] == "true"){
			if($_POST['username'] == "" || $_POST['password'] == ""){
				echo "false";
				return;
			} else {
				$ch = curl_init();
				curl_setopt($ch, CURLOPT_URL, 'http://themify.me/member/login.php');
				curl_setopt ($ch, CURLOPT_POST, 1);
				curl_setopt ($ch, CURLOPT_POSTFIELDS, 'amember_login='.$_POST['username'].'&amember_pass='.$_POST['password']);
				curl_setopt ($ch, CURLOPT_COOKIEJAR, 'cookie.txt');
				curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
				$store = curl_exec ($ch);
				curl_setopt($ch, CURLOPT_URL, $url);
				$content = curl_exec ($ch);
				curl_close ($ch);	
				unlink('cookie.txt');
				if(strpos($content, "301", 0) !== false || strpos($content, "302", 0) !== false){
					echo "false";	
					return;
				}
			}
		} else {
			$content = themify_get_file($url);
		}
		if(!is_dir(get_template_directory().'/temp')){		
			mkdir(get_template_directory().'/temp', 0777);
		}
		$newfile = get_template_directory().'/temp/temp.zip';
		if(!$fh=fopen($newfile, 'w')){
			echo "false";
			return;
		} else {
			fwrite($fh, $content);
			fclose($fh);			
			
			if(function_exists('themify_unzip')){
				themify_unzip('../temp/temp.zip', $dest);	
			} else {
				echo "false";
				return;
			}
			$handle = opendir("../temp/");
			while($file = readdir($handle)){
				if($file != "." && $file != ".."){
					unlink("../temp/".$file);
				}
			}
			rmdir("../temp/");
			echo "true";
			return;
		}
	}
	
?>