<?php

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*		Themify Framework v.1.1.0
/*		http://themify.me
/*		
/*		Copyright 2011, Darcy Clarke
/*		Dual licensed under the MIT or GPL Version 2 licenses.
/*		http://themify.me/license.txt
/*
/***************************************************************************/
	
/* 	Global Configuration
/***************************************************************************/
	
	error_reporting(E_ERROR);
	
	global $themify_globals;
	$themify_globals = array();
	$themify_globals['errors'] = array();
	$themify_globals['notifications'] = array();
	
	///////////////////////////////////////////
	// Theme Activation
	///////////////////////////////////////////
	if(isset($_GET['activated']) && $pagenow == "themes.php"){
		do_action('themify_activate_theme');
	}	
			
	///////////////////////////////////////////
	// Theme Variables
	///////////////////////////////////////////
	$themify_globals['wpurl'] = get_bloginfo('wpurl')."/";
	$themify_globals['admin_url'] = $themify_globals['wpurl']."/wp-admin/";
	$themify_globals['template_url'] = get_bloginfo('template_directory')."/";
	$themify_globals['framework_url'] = $themify_globals['template_url']."/themify/";
	$themify_globals['version'] = "1.1.0";
	$themify_globals['theme'] = get_theme_data(get_template_directory() . '/style.css');
	$themify_globals['templates'] = array();

	///////////////////////////////////////////
	// Database Configuration
	///////////////////////////////////////////
	themify_init_db();
	$themify_globals['data'] = themify_get_data();
		
	///////////////////////////////////////////
	// Generate Config from XML	
	///////////////////////////////////////////
	if(is_file(get_template_directory()."/custom-config.xml")){
		$config = themify_xml2array(themify_get_file(get_template_directory()."/custom-config.xml"));
		$themify_globals['config'] = $config['config']['_c'];
	} else if(is_file(get_template_directory()."/theme-config.xml")){
		$config = themify_xml2array(themify_get_file(get_template_directory()."/theme-config.xml"));
		$themify_globals['config'] = $config['config']['_c'];
	} else {
		$themify_globals['errors']['config'] = "No 'theme-config.xml' file found";
	}

	///////////////////////////////////////////
	// Create Panels from Config
	///////////////////////////////////////////				
	if($themify_globals['config']){
		$panels = $themify_globals['config']['panel'];
		unset($themify_globals['config']['panel']);
		if(is_array($panels)){
			foreach($panels as $panel){
				$themify_globals['config']['panel'][strtolower($panel['_a']['title'])] = $panel['_c'];
			}
		} else {
			$themify_globals['errors']['panels'] = "Could not create option panels. Check 'config.xml' for formatting/parsing issues.";
		}
		unset($panels);
		unset($config);
	}
	
	///////////////////////////////////////////
	// Init Themify
	///////////////////////////////////////////
	do_action('themify_init');
	
?>