<?php

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*		Themify Framework v.1.1.0
/*		http://themify.me
/*		
/*		Copyright 2011, Darcy Clarke
/*		Dual licensed under the MIT or GPL Version 2 licenses.
/*		http://themify.me/license.txt
/*
/***************************************************************************/

/* 	Database Functions
/***************************************************************************/
	
	///////////////////////////////////////////
	// Check for $wpdb Object with Backups
	///////////////////////////////////////////
	global $wpdb, $themify_globals;
	if(!isset($wpdb)){
		if(!isset($themify_globals)){
			$themify_globals = array();
		}
		$themify_globals['table_prefix'] = $table_prefix;
		require_once('includes/ez_sql_core.php');
		require_once('includes/ez_sql_mysql.php');
		$wpdb = new ezSQL_mysql(DB_USER, DB_PASSWORD, DB_NAME, DB_HOST);
	}
	
	///////////////////////////////////////////
	// Initialize DB - Create Row if needed
	///////////////////////////////////////////
	function themify_init_db(){
		global $wpdb, $themify_globals;
		if($wpdb->options){
			$themify_globals['wp_options'] = $wpdb->options;
		} else {
			$themify_globals['wp_options'] = $themify_globals['table_prefix']."options";
		}
		if(!$wpdb->get_row("SELECT * FROM ".$themify_globals['wp_options']." WHERE option_name = '".$themify_globals['theme']['Name']."_themify_data'")){
			$wpdb->query("INSERT INTO ".$themify_globals['wp_options']." SET option_name = '".$themify_globals['theme']['Name']."_themify_data', option_value = '', autoload = 'yes'");
		}
	}
		
	///////////////////////////////////////////
	// Set/Save Data
	///////////////////////////////////////////
	function themify_set_data($data){
		global $wpdb, $themify_globals;
		themify_init_db();
		foreach($data as $name => $value){
			if($name == 'save' || $name == 'page'){
				unset($data[$name]);	
			}
		}
		$result = $wpdb->query("UPDATE ".$themify_globals['wp_options']." SET option_value = '".base64_encode(serialize($data))."' WHERE option_name = '".$themify_globals['theme']['Name']."_themify_data'");
		return $data;
	}
		
	///////////////////////////////////////////
	// Get/Grab Data
	///////////////////////////////////////////
	function themify_get_data(){
		global $wpdb, $themify_globals;
		themify_init_db();
		$result = $wpdb->get_row("SELECT * FROM ".$themify_globals['wp_options']." WHERE option_name = '".$themify_globals['theme']['Name']."_themify_data'");
		$data = unserialize(base64_decode($result->option_value));
		if(is_array($data) && count($data) >= 1){
			foreach($data as $name => $value){
				$data[$name] = stripslashes($value);	
			}
		}
		return $data;
	}
	
	///////////////////////////////////////////
	// Backwards compatible Function Reference
	///////////////////////////////////////////
	if(!function_exists("get_data")){
		function get_data(){
			return themify_get_data();
		}
	}
	
	///////////////////////////////////////////
	// Catch error and potential conflicts
	///////////////////////////////////////////
	add_action('themify_init', 'themify_hook_get_data');
	function themify_hook_get_data(){
		global $themify_globals;		
		if(function_exists("get_data")){
			$themify_globals['errors']['function'] = "Function 'get_data()' already exists in another plugin.";
		}
	}	
	
?>