<?php

/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 						DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*		Themify Framework v.1.1.0
/*		http://themify.me
/*		
/*		Copyright 2011, Darcy Clarke
/*		Dual licensed under the MIT or GPL Version 2 licenses.
/*		http://themify.me/license.txt
/*
/***************************************************************************/

/*  Binding Hooks
/***************************************************************************/	
	
	///////////////////////////////////////////
	// Bind to Themify Init
	///////////////////////////////////////////
	add_action('themify_init', 'themify_hook_init');
	function themify_hook_init(){
		global $themify_globals;
		
		add_shortcode('is_logged_in', 'themify_shortcode');
		add_shortcode('is_guest', 'themify_shortcode');
		add_shortcode('button', 'themify_shortcode');
		add_shortcode('quote', 'themify_shortcode');
		add_shortcode('col', 'themify_shortcode');
		add_shortcode('img', 'themify_shortcode');
		add_shortcode('hr', 'themify_shortcode');
		add_shortcode('map', 'themify_shortcode');
		add_shortcode('video', 'themify_shortcode');
		
		themify_register_template('write_panel', 'themify_template_write_panel');
		themify_register_template('image', 'themify_template_image');
		themify_register_template('dropdown', 'themify_template_dropdown');
		themify_register_template('textbox', 'themify_template_textbox');
		themify_register_template('checkbox', 'themify_template_checkbox');
		themify_register_template('layout', 'themify_template_layout');
		themify_register_template('query_category', 'themify_template_query_category');
		themify_register_template('sidebar_visibility', 'themify_template_sidebar_visibility');
		themify_register_template('framework_page', 'themify_template_framework_page');
		
			
		if(is_super_admin() || current_user_can('edit_theme_options')){
			add_action('admin_menu', 'themify_hook_admin_menu');
		} else {
			$themify_globals['errors']['permission'] = "User does not have access to view option panel";
		}
		
		add_filter('widget_text','do_shortcode');
		
		add_action('wp_head', 'themify_get_css');
	}
	
	function themify_hook_admin_menu(){
		global $themify_globals;		
		add_object_page('themify', $themify_globals['theme']['Name'], 1, 'themify', 'themify_page', get_bloginfo('template_directory').'/themify/img/favicon.png');
		add_submenu_page('themify', $themify_globals['theme']['Name'], 'Theme Options', 1, 'themify', 'themify_page');
	}
	
	///////////////////////////////////////////
	// Bind to Themify CSS
	///////////////////////////////////////////
	add_action('admin_init', 'themify_hook_css');
	function themify_hook_css(){ 
		global $themify_globals;
		wp_enqueue_style('themify-ui-css', $themify_globals['framework_url'].'css/themify-ui.css', array(), false, 'all');
	}
	
	///////////////////////////////////////////
	// Bind to Themify JS Libraries 
	///////////////////////////////////////////
	add_action('admin_init', 'themify_hook_js');
	function themify_hook_js(){
		global $themify_globals;
		wp_enqueue_script('themify-jquery', $themify_globals['framework_url'].'js/jquery.js', array(), false, true);
		wp_enqueue_script('themify-check', $themify_globals['framework_url'].'js/jquery.check.js', array(), false, true);
		wp_enqueue_script('themify-jqueryui', $themify_globals['framework_url'].'js/jquery.ui.js', array(), false, true);
		wp_enqueue_script('themify-tabs', $themify_globals['framework_url'].'js/jquery.tabs.js', array(), false, true);
		wp_enqueue_script('themify-clickoutside', $themify_globals['framework_url'].'js/jquery.clickoutside.js', array(), false, true);
		wp_enqueue_script('themify-swfobject', $themify_globals['framework_url'].'js/swfobject.js', array(), false, true);
		wp_enqueue_script('themify-uploadify', $themify_globals['framework_url'].'js/jquery.uploadify.min.js', array(), false, true);
		wp_enqueue_script('themify-colorpicker', $themify_globals['framework_url'].'js/colorpicker.js', array(), false, true);
		wp_enqueue_script('themify-scripts', $themify_globals['framework_url'].'js/scripts.js', array(), false, true);
		
	}
	
	///////////////////////////////////////////
	// Bind to Save Post - Save Meta Boxes
	///////////////////////////////////////////
	add_action('save_post', 'themify_save_postdata');
	function themify_save_postdata( $post_id ) {  
		global $post, $themify_globals;
		if(isset($_POST['themify_proper_save']) && $_POST['themify_proper_save'] != '') {
			foreach($themify_globals['write_panels'] as $write_panel){
				foreach($write_panel['options'] as $meta_box) {  
					if ( 'page' == $_POST['post_type'] ) {  
						if ( !current_user_can( 'edit_page', $post_id ))  
						return $post_id;  
					} else {  
						if ( !current_user_can( 'edit_post', $post_id ))  
						return $post_id;  
					}  
					$data = $_POST[$meta_box['name']];
					
					if(get_post_meta($post_id, $meta_box['name']) == "")  
					add_post_meta($post_id, $meta_box['name'], $data, true);  
					elseif($data != get_post_meta($post_id, $meta_box['name'], true))  
					update_post_meta($post_id, $meta_box['name'], $data); 
				}  
			}
		} else {
			return $post->ID;	
		}
	}   
	
	///////////////////////////////////////////
	// Bind to Admin Menu - Create Meta Boxes
	///////////////////////////////////////////
	add_action('admin_menu', 'themify_hook_create_meta_boxes');
	function themify_hook_create_meta_boxes(){
		global $themify_globals;
		if(function_exists('add_meta_box')){
			foreach($themify_globals['write_panels'] as $args){
				if($args['pages'] != ''){
					$themify_meta_page = $args['pages'];
				} else {
					$themify_meta_page = 'post';	
				}
				if($args['name'] != ''){
					$themify_meta_name = $args['name'];	
				} else {
					$themify_meta_name = 'Themify Options';
				}
				$pages = explode(",", $themify_meta_page);
				foreach($pages as $page){
					add_meta_box( 'themify-meta-boxes', 'Themify Custom Panel', 'themify_meta_boxes', trim($page), 'normal', 'high' ); 
				}
			}
		} else {
			$themify_globals['errors']['meta_box'] = "Your version of WordPress does not support meta_boxes";
		}
	}
	function themify_meta_boxes(){
		global $post, $themify_globals;  
		foreach($themify_globals['write_panels'] as $write_panel){
			$pages = explode(",", $write_panel['pages']);
			$check = false;
			foreach($pages as $page){
				if(get_post_type($post)){
					if(get_post_type($post) == $page){
						$check = true;	
					}
				} else {
					if((trim($page) == 'post' && $_GET['post_type'] == '') || $_GET['post_type'] == trim($page)){
						$check = true;	
					}
				}
			}
			if($check){
				do_action('themify_before_write_panel');
				themify_render_template('write_panel', $write_panel);
				do_action('themify_after_write_panel');
			}
		}
	}	
?>